spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orm
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jackson:
    serialization:
      indent-output: true